### ISSUE TITLE
Selfhosted Emails with Sendgrid

### ISSUE THREAD

**Issue by Fokarr** [D1ceWard/plausible_on_dokku#13]
**Describe the bug**
E-Mails are not getting sent on self-hosted version with sendgrid

**To Reproduce**
I am reproducing this when I try to reset my password

**Screenshots**
This is the docker log from the mail container
`Connecting to aspmx.l.google.com [xxxx:xxxx:xxxx:c07::1b]:25 ... failed: Cannot assign requested address
H=aspmx.l.google.com [xxxx:xxxx:xxxx:c07::1b] Cannot assign requested address
`

**Additional context**
This is my docker-compose.yaml
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      MAILER_EMAIL: no-reply@exord.de
      SMTP_HOST_ADDR: smtp.sendgrid.net
      SMTP_HOST_PORT: 587
      SMTP_HOST_SSL_ENABLED: 1
      SMTP_USER_NAME: apikey
      SMTP_USER_PWD: SENDGRID_API_PASSWORD

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

```
